# example netlify.toml
[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "build"

[build.processing.css]
    bundle = false
    minify = false

[functions]
  node_bundler = "esbuild" 


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
